#
# Project Euler problem solution
#

include ../problem.mk
include ../sys.mk
include ../tools.mk
include ../flags.mk

OBJS=main.o poker.o print.o

include ../build.mk

main.o: main.c poker.h
print.o: print.c poker.h
poker.o: poker.c poker.h
