#
# Project Euler problem solution
#

include ../problem.mk
include ../sys.mk
include ../tools.mk
include ../flags.mk

CFLAGS += -fgcse-las -faggressive-loop-optimizations -fdelete-null-pointer-checks -fwhole-program

OBJS=main.o

include ../build.mk

